<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.0 on win32)" generated="20210106 16:02:34.784" rpa="false">
<suite id="s1" name="1" source="C:\Users\Ayan Dutta\PycharmProjects\Automation\REST API\1.robot">
<test id="s1-t1" name="Get_WeatherInfo">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>mysession</arg>
<arg>${base_url}</arg>
</arguments>
<msg timestamp="20210106 16:02:35.044" level="INFO">Creating Session using : alias=mysession, url=https://https://www.indiabix.com, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20210106 16:02:35.028" endtime="20210106 16:02:35.044"></status>
</kw>
<kw name="Get Request" library="RequestsLibrary">
<doc>Send a GET request on the session object found using the
given `alias`</doc>
<arguments>
<arg>mysession</arg>
<arg>/computer-science/${sub}</arg>
</arguments>
<assign>
<var>${response}</var>
</assign>
<msg timestamp="20210106 16:02:35.044" level="INFO">GET Request using : uri=/computer-science/questions-and-answers, params=None, allow_redirects=True, timeout=None
headers={'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
data=None 
json=None</msg>
<msg timestamp="20210106 16:02:37.336" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE550&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
<msg timestamp="20210106 16:02:39.808" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE5F8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
<msg timestamp="20210106 16:02:42.480" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE628&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
<msg timestamp="20210106 16:02:44.747" level="FAIL">ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //www.indiabix.com/computer-science/questions-and-answers (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE6D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</msg>
<status status="FAIL" starttime="20210106 16:02:35.044" endtime="20210106 16:02:44.747"></status>
</kw>
<status status="FAIL" starttime="20210106 16:02:35.028" endtime="20210106 16:02:44.747" critical="yes">ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //www.indiabix.com/computer-science/questions-and-answers (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE6D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</status>
</test>
<status status="FAIL" starttime="20210106 16:02:34.784" endtime="20210106 16:02:44.747"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="1">1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210106 16:02:37.336" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE550&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
<msg timestamp="20210106 16:02:39.808" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE5F8&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
<msg timestamp="20210106 16:02:42.480" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x038DE628&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //www.indiabix.com/computer-science/questions-and-answers</msg>
</errors>
</robot>
